---
- hosts: all
  become: yes

  vars:
    # Vars can also be passed in via CLI with `--extra-vars="name=value"`.
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      register: result
      until: '"failed" not in result'
      retries: 5
      delay: 10

    - name: Import EPEL GPG key.
      rpm_key:
        key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present

    - name: Import Remi GPG key.
      rpm_key: "key={{ item }} state=present"
      with_items:
        - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"

    - name: Install Remi repo.
      command: "rpm -Uvh --force {{ item.href }} creates={{ item.creates }}"
      with_items:
        - href: "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
          creates: "/etc/yum.repos.d/remi.repo"

    - name: Ensure firewalld is stopped (since this is a test server).
      service: name=firewalld state=stopped

    - name: Install Node.js and npm.
      yum: name=npm state=present enablerepo=epel

    - name: Install Forever (to run our Node.js app).
      npm: name=forever global=yes state=present

    - name: Ensure Node.js app folder exists.
      file: "path={{ node_apps_location }} state=directory"

    - name: Copy example Node.js app to server.
      copy: "src=app dest={{ node_apps_location }}"

    - name: Install app dependencies defined in package.json.
      npm: "path={{ node_apps_location }}/app"

    - name: Check list of running Node.js apps.
      command: forever list
      register: forever_list
      changed_when: false

    - name: Start example Node.js app.
      command: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find('{{ node_apps_location }}/app/app.js') == -1"
